// <auto-generated />
namespace LagerHantering.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class databaseupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databaseupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201705101341562_database-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
